- name: Replace binary to the latest on Raspberry Pi 
  hosts: rpi
  user: pi 
  gather_facts: yes
  
  vars:
    hkcam_download_dir: /home/pi

  tasks:
    - name: Copy shellscript to Raspberry Pi
      copy: 
        src: files/update.sh
        dest: "{{ hkcam_download_dir }}"
        mode: u=rwx,g=rwx,o=r
    
    - name: Execute update.sh
      shell: sh update.sh