- name: Replace binary to the latest on Raspberry Pi 
  hosts: rpi
  user: pi 
  gather_facts: yes
  
  vars:
    hkcam_download_dir: /home/pi

  tasks:
    - name: Copy shellscript to Raspberry Pi
      copy: 
        src: files/update.sh
        dest: "{{ hkcam_download_dir }}"
        mode: u=rwx,g=rwx,o=r 

    - name: Make an cronjob 
      cron:
        name: "Cronjob for update"
        minute: "0"
        hour: "0"
        job: "{{ hkcam_download_dir }}/update.sh"

    - name: Execute update.sh
      shell: /bin/bash/update.sh